name: Teste do dispatch e needs

on:
  push:
    branches:
      - main
    paths:
      - 'teste/**'          # Só roda se houver alterações em arquivos dentro de lib/
      # Adicione outras pastas ou arquivos conforme necessário


  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
              - web
              - macOs
              - android

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs: 
        env_is_valid: ${{ steps.checar_env.outputs.valid }}
    steps:
        - name: Lista diretorio
          run: ls -la
        - name: Gera saida do github context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Dados 
          run: echo "${{ github.event.inputs.environment }}"  
        - name: Check Environment
          id: checar_env
          run: |
            # Set the value (e.g., true/false)
            echo "valid=true" >> "$GITHUB_OUTPUT"
   
  print-env:
    needs: [set-environment]
    env:
        GIT_VAR: ${{ needs }}  
   # if: needs.checar_env.outputs.env_is_valid == 'true'
    runs-on: ubuntu-latest
    steps:
        - name: Lista diretorio
          run: echo "env_is_valid"
        - name: Verifca se variavel setada
          run: echo "$GIT_VAR"
