name: Deploy Flutter Web to FTP (Integrator)

on:
  push:
    branches:
      - main
    paths:
      - 'teste/**'          # Só roda se houver alterações em arquivos dentro de lib/
      # Adicione outras pastas ou arquivos conforme necessário


  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
              - web
              - macOs
              - android
jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs: 
        env_is_valid: ${{ steps.checar_env.outputs.valid }}
    steps:
        - name: Lista diretorio
          run: ls -la
#        - name: Gera saida do github context
#          run: echo "${{ toJSON(github) }}"
        - name: Dados 
          run: echo "${{ github.event.inputs.environment }}"  